# Generated by Django 5.2.4 on 2025-08-19 22:47

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('inventory', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='printer',
            name='dummy_field',
        ),
    ]
