# Generated by Django 5.2.4 on 2025-07-28 00:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inventory', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='inventoryitem',
            name='photo_path',
        ),
        migrations.RemoveField(
            model_name='printer',
            name='photo_path',
        ),
        migrations.RemoveField(
            model_name='project',
            name='photo_path',
        ),
        migrations.AddField(
            model_name='inventoryitem',
            name='photo',
            field=models.ImageField(blank=True, null=True, upload_to='inventory_photos/'),
        ),
        migrations.AddField(
            model_name='printer',
            name='photo',
            field=models.ImageField(blank=True, null=True, upload_to='printer_photos/'),
        ),
        migrations.AddField(
            model_name='project',
            name='photo',
            field=models.ImageField(blank=True, null=True, upload_to='project_photos/'),
        ),
    ]
