# Generated by Django 5.2.4 on 2025-07-28 22:00

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inventory', '0002_remove_inventoryitem_photo_path_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='printer',
            name='carbon_reminder_date',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='printer',
            name='last_carbon_replacement_date',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='printer',
            name='maintenance_reminder_date',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.CreateModel(
            name='Mod',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('link', models.URLField(blank=True, max_length=512, null=True)),
                ('file', models.FileField(blank=True, null=True, upload_to='mod_files/')),
                ('printer', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='mods', to='inventory.printer')),
            ],
        ),
    ]
