# Generated by Django 5.2.4 on 2025-10-18 06:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inventory', '0003_alter_modfile_file_alter_projectfile_file_tracker_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='trackerfile',
            name='github_url',
            field=models.URLField(blank=True, help_text='Direct URL to the file on GitHub', max_length=512, null=True),
        ),
    ]
