# Generated by Django 5.2.4 on 2025-07-28 22:20

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inventory', '0003_printer_carbon_reminder_date_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='mod',
            name='file',
        ),
        migrations.CreateModel(
            name='ModFile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('file', models.FileField(upload_to='mod_files/')),
                ('mod', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='files', to='inventory.mod')),
            ],
        ),
    ]
