# Generated by Django 5.2.4 on 2025-07-29 22:17

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inventory', '0004_remove_mod_file_modfile'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='project',
            name='associated_files',
        ),
        migrations.AlterField(
            model_name='printer',
            name='status',
            field=models.CharField(choices=[('Active', 'Active'), ('Under Repair', 'Under Repair'), ('Sold', 'Sold'), ('Archived', 'Archived'), ('Planned', 'Planned')], default='Active', max_length=50),
        ),
        migrations.CreateModel(
            name='ProjectFile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('file', models.FileField(upload_to='project_files/')),
                ('project', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='files', to='inventory.project')),
            ],
        ),
        migrations.CreateModel(
            name='ProjectLink',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('url', models.URLField(max_length=512)),
                ('project', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='links', to='inventory.project')),
            ],
        ),
    ]
