# Generated by Django 5.2.4 on 2025-10-18 22:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inventory', '0004_alter_trackerfile_github_url'),
    ]

    operations = [
        migrations.AddField(
            model_name='tracker',
            name='printed_quantity_total',
            field=models.IntegerField(default=0, help_text='Total quantity of printed parts'),
        ),
        migrations.AddField(
            model_name='tracker',
            name='progress_percentage',
            field=models.IntegerField(default=0, help_text='Completion percentage (0-100)'),
        ),
        migrations.AddField(
            model_name='tracker',
            name='total_quantity',
            field=models.IntegerField(default=0, help_text='Total quantity of all parts'),
        ),
    ]
