# Generated by Django 5.2.4 on 2025-10-18 22:57

from django.db import migrations
from django.db.models import Sum


def populate_tracker_stats(apps, schema_editor):
    """Populate cached statistics for existing trackers."""
    Tracker = apps.get_model('inventory', 'Tracker')
    
    for tracker in Tracker.objects.all():
        # Calculate statistics
        quantity_result = tracker.files.aggregate(total=Sum('quantity'))
        printed_result = tracker.files.aggregate(total=Sum('printed_quantity'))
        
        tracker.total_quantity = quantity_result['total'] or 0
        tracker.printed_quantity_total = printed_result['total'] or 0
        
        if tracker.total_quantity == 0:
            tracker.progress_percentage = 0
        else:
            tracker.progress_percentage = round((tracker.printed_quantity_total / tracker.total_quantity) * 100)
        
        tracker.save(update_fields=['total_quantity', 'printed_quantity_total', 'progress_percentage'])


def reverse_populate(apps, schema_editor):
    """Reverse migration - reset statistics to 0."""
    Tracker = apps.get_model('inventory', 'Tracker')
    Tracker.objects.all().update(
        total_quantity=0,
        printed_quantity_total=0,
        progress_percentage=0
    )


class Migration(migrations.Migration):

    dependencies = [
        ('inventory', '0005_add_cached_tracker_stats'),
    ]

    operations = [
        migrations.RunPython(populate_tracker_stats, reverse_populate),
    ]
