# Generated by Django 5.2.4 on 2025-07-30 19:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inventory', '0005_remove_project_associated_files_alter_printer_status_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='mod',
            name='status',
            field=models.CharField(choices=[('Planned', 'Planned'), ('In Progress', 'In Progress'), ('Completed', 'Completed')], default='Planned', max_length=50),
        ),
    ]
