# Generated by Django 5.2.4 on 2025-10-19 16:37

from django.db import migrations


def populate_materials(apps, schema_editor):
    """Add default materials"""
    Material = apps.get_model('inventory', 'Material')
    
    default_materials = [
        'ABS',
        'ASA',
        'HIPS',
        'Nylon',
        'PC',
        'PETG',
        'PLA',
        'PLA+',
        'TPU',
        'Other',
    ]
    
    for material_name in default_materials:
        Material.objects.get_or_create(name=material_name)


def reverse_populate(apps, schema_editor):
    """Remove default materials"""
    Material = apps.get_model('inventory', 'Material')
    Material.objects.filter(name__in=[
        'ABS', 'ASA', 'HIPS', 'Nylon', 'PC', 'PETG', 'PLA', 'PLA+', 'TPU', 'Other'
    ]).delete()


class Migration(migrations.Migration):

    dependencies = [
        ('inventory', '0007_add_material_model'),
    ]

    operations = [
        migrations.RunPython(populate_materials, reverse_populate),
    ]
