# Generated by Django 5.2.4 on 2025-10-19 17:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inventory', '0008_populate_default_materials'),
    ]

    operations = [
        migrations.AddField(
            model_name='tracker',
            name='creation_mode',
            field=models.CharField(choices=[('github', 'GitHub Wizard'), ('manual', 'Manual Creation')], default='github', help_text='How this tracker was created', max_length=10),
        ),
        migrations.AlterField(
            model_name='tracker',
            name='github_url',
            field=models.URLField(blank=True, help_text='GitHub repository URL where files are located', max_length=512),
        ),
    ]
