# Generated by Django 5.2.4 on 2025-10-19 22:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inventory', '0009_tracker_creation_mode_alter_tracker_github_url'),
    ]

    operations = [
        migrations.AddField(
            model_name='tracker',
            name='files_downloaded',
            field=models.BooleanField(default=False, help_text='Whether all files have been successfully downloaded'),
        ),
        migrations.AddField(
            model_name='tracker',
            name='storage_path',
            field=models.CharField(blank=True, help_text="Base storage path for this tracker's files", max_length=500),
        ),
        migrations.AddField(
            model_name='tracker',
            name='total_storage_used',
            field=models.BigIntegerField(default=0, help_text='Total bytes used by all downloaded files'),
        ),
        migrations.AddField(
            model_name='trackerfile',
            name='actual_file_size',
            field=models.BigIntegerField(blank=True, help_text='Actual size of downloaded file (may differ from estimate)', null=True),
        ),
        migrations.AddField(
            model_name='trackerfile',
            name='download_error',
            field=models.TextField(blank=True, help_text='Error message if download failed'),
        ),
        migrations.AddField(
            model_name='trackerfile',
            name='download_status',
            field=models.CharField(choices=[('pending', 'Pending'), ('downloading', 'Downloading'), ('completed', 'Completed'), ('failed', 'Failed')], default='pending', help_text='Current download status of this file', max_length=20),
        ),
        migrations.AddField(
            model_name='trackerfile',
            name='downloaded_at',
            field=models.DateTimeField(blank=True, help_text='When file was successfully downloaded', null=True),
        ),
        migrations.AddField(
            model_name='trackerfile',
            name='file_checksum',
            field=models.CharField(blank=True, help_text='SHA256 checksum of downloaded file for integrity verification', max_length=64),
        ),
    ]
