# Generated by Django 5.2.4 on 2025-10-20 02:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inventory', '0010_tracker_files_downloaded_tracker_storage_path_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='tracker',
            name='github_url',
            field=models.TextField(blank=True, default='', help_text='GitHub repository URL where files are located'),
        ),
        migrations.AlterField(
            model_name='trackerfile',
            name='github_url',
            field=models.TextField(blank=True, default='', help_text='Direct URL to the file on GitHub'),
        ),
    ]
