# Generated by Django 5.2.4 on 2025-10-21 18:23

import inventory.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inventory', '0012_trackerfile_storage_type'),
    ]

    operations = [
        migrations.AlterField(
            model_name='trackerfile',
            name='local_file',
            field=models.FileField(blank=True, help_text='Local copy of the file (if downloaded)', max_length=500, null=True, upload_to=inventory.models.get_tracker_upload_path),
        ),
    ]
