# Generated by Django 5.2.4 on 2025-10-28 03:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inventory', '0013_increase_tracker_file_path_length'),
    ]

    operations = [
        migrations.AddField(
            model_name='project',
            name='due_date',
            field=models.DateField(blank=True, help_text='Project deadline/due date for tracking purposes', null=True),
        ),
        migrations.AddField(
            model_name='tracker',
            name='show_on_dashboard',
            field=models.BooleanField(default=False, help_text='Display this tracker in the dashboard featured section'),
        ),
        migrations.CreateModel(
            name='AlertDismissal',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('alert_type', models.CharField(help_text='Type of alert (e.g., maintenance_overdue, low_stock, etc.)', max_length=50)),
                ('alert_id', models.CharField(help_text='Unique identifier for the specific alert instance', max_length=100)),
                ('dismissed_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'verbose_name': 'Alert Dismissal',
                'verbose_name_plural': 'Alert Dismissals',
                'indexes': [models.Index(fields=['alert_type', 'alert_id'], name='inventory_a_alert_t_ee7fbe_idx')],
                'unique_together': {('alert_type', 'alert_id')},
            },
        ),
    ]
