# Generated by Django 5.2.4 on 2025-10-28 04:45

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('inventory', '0014_project_due_date_tracker_show_on_dashboard_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='project',
            name='end_date',
        ),
    ]
