# Generated by Django 5.2.4 on 2025-10-28 05:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inventory', '0015_remove_project_end_date'),
    ]

    operations = [
        migrations.AddField(
            model_name='alertdismissal',
            name='state_hash',
            field=models.CharField(blank=True, help_text='SHA256 hash of the state that caused this alert (for invalidation detection)', max_length=64, null=True),
        ),
    ]
