# Generated by Django 5.2.4 on 2025-11-11 03:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inventory', '0017_vendor_inventoryitem_model_inventoryitem_vendor_link_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='tracker',
            name='notes',
            field=models.TextField(blank=True, help_text='Optional notes about this tracker', null=True),
        ),
    ]
