# Generated by Django 5.2.4 on 2025-12-11 19:44

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inventory', '0018_tracker_notes'),
    ]

    operations = [
        migrations.CreateModel(
            name='FilamentSpool',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('color_name', models.CharField(help_text="Color name (e.g., 'Galaxy Black', 'Fire Engine Red')", max_length=100)),
                ('color_hex', models.CharField(help_text="Hex color code (e.g., '#1a1a1a')", max_length=7)),
                ('quantity', models.IntegerField(default=1, help_text='Number of identical unopened spools (default: 1)')),
                ('is_opened', models.BooleanField(default=False, help_text='True if spool is opened/in use (locks quantity to 1)')),
                ('initial_weight', models.IntegerField(help_text='Starting weight in grams')),
                ('current_weight', models.IntegerField(help_text='Current weight in grams (updated as filament is used)')),
                ('status', models.CharField(choices=[('new', 'New/Unopened'), ('active', 'Active'), ('in_use', 'In Use (On Printer)'), ('low', 'Low Stock'), ('empty', 'Empty'), ('archived', 'Archived')], default='new', max_length=20)),
                ('date_added', models.DateTimeField(auto_now_add=True)),
                ('date_opened', models.DateTimeField(blank=True, help_text='When spool was first opened/used', null=True)),
                ('date_emptied', models.DateTimeField(blank=True, help_text='When spool was marked empty', null=True)),
                ('date_archived', models.DateTimeField(blank=True, help_text='When spool was archived', null=True)),
                ('notes', models.TextField(blank=True, help_text='User notes about this spool')),
                ('nfc_tag_id', models.CharField(blank=True, help_text='NFC tag identifier (optional)', max_length=255, unique=True)),
            ],
            options={
                'verbose_name': 'Filament Spool',
                'verbose_name_plural': 'Filament Spools',
                'ordering': ['-date_added'],
            },
        ),
        migrations.AddField(
            model_name='material',
            name='base_material',
            field=models.ForeignKey(blank=True, help_text='Generic material type (PLA, PETG, etc.)', limit_choices_to={'is_generic': True}, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='blueprints', to='inventory.material'),
        ),
        migrations.AddField(
            model_name='material',
            name='brand',
            field=models.ForeignKey(blank=True, help_text='Manufacturer (e.g., Sunlu, eSun)', null=True, on_delete=django.db.models.deletion.CASCADE, to='inventory.brand'),
        ),
        migrations.AddField(
            model_name='material',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, null=True),
        ),
        migrations.AddField(
            model_name='material',
            name='diameter',
            field=models.DecimalField(blank=True, decimal_places=2, help_text='Filament diameter in mm (typically 1.75 or 2.85)', max_digits=4, null=True),
        ),
        migrations.AddField(
            model_name='material',
            name='favorite_order',
            field=models.IntegerField(blank=True, help_text='Display order in favorites list (1-5)', null=True),
        ),
        migrations.AddField(
            model_name='material',
            name='is_favorite',
            field=models.BooleanField(default=False, help_text='Mark as favorite (max 5)'),
        ),
        migrations.AddField(
            model_name='material',
            name='is_generic',
            field=models.BooleanField(default=True, help_text='True for generic types (PLA, PETG), False for specific products'),
        ),
        migrations.AddField(
            model_name='material',
            name='low_stock_threshold',
            field=models.IntegerField(blank=True, help_text='Alert when total grams falls below this value', null=True),
        ),
        migrations.AddField(
            model_name='material',
            name='photo',
            field=models.ImageField(blank=True, help_text='Product photo, shown for all spools using this blueprint', null=True, upload_to='filament_photos/'),
        ),
        migrations.AddField(
            model_name='material',
            name='price_per_spool',
            field=models.DecimalField(blank=True, decimal_places=2, help_text="Price in USD (or user's currency)", max_digits=8, null=True),
        ),
        migrations.AddField(
            model_name='material',
            name='spool_weight',
            field=models.IntegerField(blank=True, help_text='Typical spool weight in grams (e.g., 1000 for 1kg)', null=True),
        ),
        migrations.AddField(
            model_name='material',
            name='tds_value',
            field=models.IntegerField(blank=True, help_text='Translucency (TDS) value for HueForge lithophanes', null=True),
        ),
        migrations.AddField(
            model_name='material',
            name='updated_at',
            field=models.DateTimeField(auto_now=True, null=True),
        ),
        migrations.AddField(
            model_name='material',
            name='vendor',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='inventory.vendor'),
        ),
        migrations.AddField(
            model_name='material',
            name='vendor_link',
            field=models.URLField(blank=True, help_text='Direct link to product page for reordering'),
        ),
        migrations.AddField(
            model_name='tracker',
            name='primary_filament_used_grams',
            field=models.IntegerField(blank=True, help_text='Estimated or measured grams of primary filament used', null=True),
        ),
        migrations.AddField(
            model_name='tracker',
            name='secondary_filament_used_grams',
            field=models.IntegerField(blank=True, help_text='Estimated or measured grams of secondary filament used', null=True),
        ),
        migrations.AlterField(
            model_name='material',
            name='name',
            field=models.CharField(max_length=255),
        ),
        migrations.AddIndex(
            model_name='material',
            index=models.Index(fields=['is_generic'], name='inventory_m_is_gene_68649f_idx'),
        ),
        migrations.AddIndex(
            model_name='material',
            index=models.Index(fields=['is_favorite'], name='inventory_m_is_favo_3378e2_idx'),
        ),
        migrations.AddConstraint(
            model_name='material',
            constraint=models.UniqueConstraint(condition=models.Q(('is_generic', False)), fields=('name', 'brand'), name='unique_material_brand_for_blueprints'),
        ),
        migrations.AddConstraint(
            model_name='material',
            constraint=models.UniqueConstraint(condition=models.Q(('is_generic', True)), fields=('name',), name='unique_name_for_generic_materials'),
        ),
        migrations.AddField(
            model_name='filamentspool',
            name='assigned_printer',
            field=models.ForeignKey(blank=True, help_text='Printer this spool is currently loaded on', null=True, on_delete=django.db.models.deletion.SET_NULL, to='inventory.printer'),
        ),
        migrations.AddField(
            model_name='filamentspool',
            name='filament_type',
            field=models.ForeignKey(help_text='Which filament blueprint (product) is this?', limit_choices_to={'is_generic': False}, on_delete=django.db.models.deletion.CASCADE, to='inventory.material'),
        ),
        migrations.AddField(
            model_name='filamentspool',
            name='location',
            field=models.ForeignKey(blank=True, help_text="Storage location (e.g., 'Storage Rack A')", null=True, on_delete=django.db.models.deletion.SET_NULL, to='inventory.location'),
        ),
        migrations.AddField(
            model_name='filamentspool',
            name='project',
            field=models.ForeignKey(blank=True, help_text='Assign to specific project (optional)', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='filaments_used', to='inventory.project'),
        ),
        migrations.AddField(
            model_name='tracker',
            name='primary_filament',
            field=models.ForeignKey(blank=True, help_text='Primary filament used for this print', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='primary_prints', to='inventory.filamentspool'),
        ),
        migrations.AddField(
            model_name='tracker',
            name='secondary_filament',
            field=models.ForeignKey(blank=True, help_text='Secondary filament (for multi-material prints)', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='secondary_prints', to='inventory.filamentspool'),
        ),
        migrations.AddIndex(
            model_name='filamentspool',
            index=models.Index(fields=['status'], name='inventory_f_status_9cac86_idx'),
        ),
        migrations.AddIndex(
            model_name='filamentspool',
            index=models.Index(fields=['assigned_printer'], name='inventory_f_assigne_f71d84_idx'),
        ),
        migrations.AddIndex(
            model_name='filamentspool',
            index=models.Index(fields=['project'], name='inventory_f_project_f63989_idx'),
        ),
    ]
