# Generated by Django 5.2.4 on 2025-12-11 20:52

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inventory', '0019_filamentspool_material_base_material_material_brand_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='filamentspool',
            name='color_hex',
        ),
        migrations.RemoveField(
            model_name='filamentspool',
            name='color_name',
        ),
        migrations.AddField(
            model_name='material',
            name='bed_temp_max',
            field=models.IntegerField(blank=True, help_text='Maximum recommended bed temperature (°C)', null=True),
        ),
        migrations.AddField(
            model_name='material',
            name='bed_temp_min',
            field=models.IntegerField(blank=True, help_text='Minimum recommended bed temperature (°C)', null=True),
        ),
        migrations.AddField(
            model_name='material',
            name='color_hex',
            field=models.CharField(blank=True, help_text="Primary color hex code (e.g., '#00FF00')", max_length=7),
        ),
        migrations.AddField(
            model_name='material',
            name='color_name',
            field=models.CharField(blank=True, help_text="Primary color name (e.g., 'Aqua Green', 'Galaxy Black')", max_length=100),
        ),
        migrations.AddField(
            model_name='material',
            name='density',
            field=models.DecimalField(blank=True, decimal_places=2, help_text='Material density in g/cm³ (e.g., 1.24 for PLA) - used for volume calculations', max_digits=4, null=True),
        ),
        migrations.AddField(
            model_name='material',
            name='nozzle_temp_max',
            field=models.IntegerField(blank=True, help_text='Maximum recommended nozzle temperature (°C)', null=True),
        ),
        migrations.AddField(
            model_name='material',
            name='nozzle_temp_min',
            field=models.IntegerField(blank=True, help_text='Minimum recommended nozzle temperature (°C)', null=True),
        ),
        migrations.AddField(
            model_name='material',
            name='secondary_color_hex',
            field=models.CharField(blank=True, help_text='Secondary color hex code for dual-color filaments', max_length=7),
        ),
        migrations.AddField(
            model_name='material',
            name='secondary_color_name',
            field=models.CharField(blank=True, help_text='Secondary color name for dual-color filaments', max_length=100),
        ),
        migrations.AlterField(
            model_name='filamentspool',
            name='filament_type',
            field=models.ForeignKey(help_text='Which filament blueprint (product) is this? Color is defined in the blueprint.', limit_choices_to={'is_generic': False}, on_delete=django.db.models.deletion.CASCADE, to='inventory.material'),
        ),
    ]
