# Generated by Django 5.2.4 on 2025-12-11 21:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inventory', '0020_remove_filamentspool_color_hex_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='material',
            name='color_hex',
        ),
        migrations.RemoveField(
            model_name='material',
            name='color_name',
        ),
        migrations.RemoveField(
            model_name='material',
            name='secondary_color_hex',
        ),
        migrations.RemoveField(
            model_name='material',
            name='secondary_color_name',
        ),
        migrations.AddField(
            model_name='material',
            name='colors',
            field=models.JSONField(blank=True, default=list, help_text="Array of color objects: [{name: 'Galaxy Black', hex: '#1a1a1a'}, ...]"),
        ),
    ]
