# Generated by Django 5.2.4 on 2025-12-11 21:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inventory', '0021_remove_material_color_hex_remove_material_color_name_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='material',
            name='notes',
            field=models.TextField(blank=True, default='', help_text='User notes/comments about this material (printing tips, quirks, etc.)'),
        ),
        migrations.AlterField(
            model_name='material',
            name='colors',
            field=models.JSONField(blank=True, default=list, help_text="Array of hex color codes: ['#1a1a1a', '#c0c0c0', ...]. Material name provides color identity."),
        ),
    ]
