# Generated by Django 5.2.4 on 2025-12-11 22:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inventory', '0022_material_notes_alter_material_colors'),
    ]

    operations = [
        migrations.AlterField(
            model_name='filamentspool',
            name='status',
            field=models.CharField(choices=[('new', 'New/Unopened'), ('opened', 'Opened'), ('in_use', 'In Use (On Printer)'), ('low', 'Low Stock'), ('empty', 'Empty'), ('archived', 'Archived')], default='new', max_length=20),
        ),
    ]
