# Generated by Django 5.2.4 on 2025-12-11 23:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inventory', '0023_alter_filamentspool_status'),
    ]

    operations = [
        migrations.AddField(
            model_name='material',
            name='empty_spool_weight',
            field=models.IntegerField(blank=True, help_text='Weight of the empty spool in grams (used for accurate remaining filament calculations)', null=True),
        ),
    ]
