# Generated by Django 5.2.4 on 2025-12-12 00:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inventory', '0024_material_empty_spool_weight'),
    ]

    operations = [
        migrations.AlterField(
            model_name='filamentspool',
            name='nfc_tag_id',
            field=models.CharField(blank=True, help_text='NFC tag identifier (optional)', max_length=255, null=True, unique=True),
        ),
    ]
