# Generated by Django 5.2.4 on 2025-12-12 00:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inventory', '0025_alter_filamentspool_nfc_tag_id'),
    ]

    operations = [
        migrations.AddField(
            model_name='material',
            name='color_family',
            field=models.CharField(blank=True, choices=[('red', 'Red'), ('orange', 'Orange'), ('yellow', 'Yellow'), ('green', 'Green'), ('blue', 'Blue'), ('purple', 'Purple'), ('pink', 'Pink'), ('brown', 'Brown'), ('black', 'Black'), ('white', 'White'), ('gray', 'Gray'), ('clear', 'Clear/Natural'), ('multi', 'Multi-Color')], help_text='Primary color family for filtering (helps with searching)', max_length=50, null=True),
        ),
    ]
