# Generated by Django 5.2.4 on 2025-12-13 00:05

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inventory', '0026_material_color_family'),
    ]

    operations = [
        migrations.AddField(
            model_name='filamentspool',
            name='standalone_bed_temp_max',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='filamentspool',
            name='standalone_bed_temp_min',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='filamentspool',
            name='standalone_color',
            field=models.CharField(blank=True, help_text="Hex color code for Quick Add spools (e.g., '#1a1a1a')", max_length=7, null=True),
        ),
        migrations.AddField(
            model_name='filamentspool',
            name='standalone_color_family',
            field=models.CharField(blank=True, choices=[('red', 'Red'), ('orange', 'Orange'), ('yellow', 'Yellow'), ('green', 'Green'), ('blue', 'Blue'), ('purple', 'Purple'), ('pink', 'Pink'), ('brown', 'Brown'), ('black', 'Black'), ('white', 'White'), ('gray', 'Gray'), ('clear', 'Clear/Natural'), ('multi', 'Multi-Color')], help_text='Color family for filtering Quick Add spools', max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='filamentspool',
            name='standalone_density',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=4, null=True),
        ),
        migrations.AddField(
            model_name='filamentspool',
            name='standalone_manufacturer',
            field=models.CharField(blank=True, help_text='Manufacturer name for Quick Add spools', max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='filamentspool',
            name='standalone_material_type',
            field=models.ForeignKey(blank=True, help_text='Generic material type for Quick Add spools (PLA, PETG, etc.)', limit_choices_to={'is_generic': True}, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='standalone_spools', to='inventory.material'),
        ),
        migrations.AddField(
            model_name='filamentspool',
            name='standalone_name',
            field=models.CharField(blank=True, help_text="Custom name for Quick Add spools (e.g., 'Convention Metallic Blue')", max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='filamentspool',
            name='standalone_nozzle_temp_max',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='filamentspool',
            name='standalone_nozzle_temp_min',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='filamentspool',
            name='standalone_photo',
            field=models.ImageField(blank=True, help_text='Photo for Quick Add spools', null=True, upload_to='filament_photos/'),
        ),
        migrations.AlterField(
            model_name='filamentspool',
            name='filament_type',
            field=models.ForeignKey(blank=True, help_text='Which filament blueprint (product) is this? Null for Quick Add spools.', limit_choices_to={'is_generic': False}, null=True, on_delete=django.db.models.deletion.CASCADE, to='inventory.material'),
        ),
    ]
