# Generated by Django 5.2.4 on 2025-12-13 00:12

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inventory', '0027_filamentspool_standalone_bed_temp_max_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='filamentspool',
            name='standalone_manufacturer',
        ),
        migrations.AddField(
            model_name='filamentspool',
            name='standalone_brand',
            field=models.ForeignKey(blank=True, help_text='Brand for Quick Add spools (uses same brands as blueprints)', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='standalone_spools', to='inventory.brand'),
        ),
    ]
