# Generated by Django 5.2.4 on 2025-12-13 00:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inventory', '0028_remove_filamentspool_standalone_manufacturer_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='filamentspool',
            name='standalone_color',
        ),
        migrations.AddField(
            model_name='filamentspool',
            name='standalone_colors',
            field=models.JSONField(blank=True, default=list, help_text="Array of hex color codes for Quick Add spools: ['#1a1a1a', '#c0c0c0', ...]. Supports gradients/multi-color filaments."),
        ),
    ]
