# Generated by Django 5.2.4 on 2025-12-13 03:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inventory', '0029_remove_filamentspool_standalone_color_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='filamentspool',
            name='price_paid',
            field=models.DecimalField(blank=True, decimal_places=2, help_text='Actual price paid for this spool (overrides blueprint list price if set)', max_digits=8, null=True),
        ),
    ]
