# Generated by Django 5.2.4 on 2025-12-13 20:25

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inventory', '0030_filamentspool_price_paid'),
    ]

    operations = [
        migrations.CreateModel(
            name='MaterialPhoto',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(help_text='Additional photo for the material', upload_to='material_additional_photos/')),
                ('caption', models.CharField(blank=True, help_text='Optional caption for this photo', max_length=255, null=True)),
                ('order', models.PositiveIntegerField(default=0, help_text='Display order (lower numbers shown first)')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('material', models.ForeignKey(help_text='The material blueprint this photo belongs to', on_delete=django.db.models.deletion.CASCADE, related_name='additional_photos', to='inventory.material')),
            ],
            options={
                'verbose_name': 'Material Photo',
                'verbose_name_plural': 'Material Photos',
                'ordering': ['order', 'created_at'],
            },
        ),
    ]
