# Generated by Django 5.2.4 on 2025-12-16 17:31

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inventory', '0032_materialfeature_material_features'),
    ]

    operations = [
        migrations.AddField(
            model_name='printer',
            name='accent_filament_blueprint',
            field=models.ForeignKey(blank=True, help_text='Material blueprint for accent filament', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='printers_using_as_accent', to='inventory.material'),
        ),
        migrations.AddField(
            model_name='printer',
            name='accent_filament_custom',
            field=models.CharField(blank=True, help_text='Custom accent filament description', max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='printer',
            name='additional_filaments',
            field=models.JSONField(blank=True, default=list, help_text="Additional filaments: [{'type': 'Top Hat', 'custom': 'Red PLA', 'blueprint_id': null}, ...]"),
        ),
        migrations.AddField(
            model_name='printer',
            name='primary_filament_blueprint',
            field=models.ForeignKey(blank=True, help_text='Material blueprint for primary filament', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='printers_using_as_primary', to='inventory.material'),
        ),
        migrations.AddField(
            model_name='printer',
            name='primary_filament_custom',
            field=models.CharField(blank=True, help_text='Custom primary filament description', max_length=255, null=True),
        ),
    ]
