# Generated by Django 5.2.4 on 2025-12-16 20:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inventory', '0033_printer_accent_filament_blueprint_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='project',
            name='materials',
            field=models.JSONField(blank=True, default=list, help_text='Array of material objects with label, type, custom_color, and blueprint_id fields'),
        ),
    ]
