# Generated by Django 5.2.4 on 2025-12-17 01:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inventory', '0034_project_materials'),
    ]

    operations = [
        migrations.AddField(
            model_name='trackerfile',
            name='material_ids',
            field=models.JSONField(blank=True, default=list, help_text='Array of Material IDs (e.g., [1, 5, 13] for multicolor)'),
        ),
        migrations.AlterField(
            model_name='project',
            name='materials',
            field=models.JSONField(blank=True, default=list, help_text='Array of material objects with label, custom_color, and blueprint_id fields'),
        ),
        migrations.AlterField(
            model_name='trackerfile',
            name='material',
            field=models.CharField(blank=True, help_text='Material name(s) for display (legacy field, use material_ids instead)', max_length=50),
        ),
    ]
