# Generated by Django 5.2.4 on 2025-12-19 00:04

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inventory', '0035_trackerfile_material_ids_alter_project_materials_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='tracker',
            name='accent_material',
            field=models.ForeignKey(blank=True, help_text='Material blueprint for accent color files', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='trackers_as_accent', to='inventory.material'),
        ),
        migrations.AddField(
            model_name='tracker',
            name='primary_material',
            field=models.ForeignKey(blank=True, help_text='Material blueprint for primary color files', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='trackers_as_primary', to='inventory.material'),
        ),
        migrations.AddField(
            model_name='trackerfile',
            name='material_override',
            field=models.BooleanField(default=False, help_text="If True, this file has custom materials and won't be updated by tracker-level material changes"),
        ),
        migrations.AlterField(
            model_name='tracker',
            name='accent_color',
            field=models.CharField(default='#DC2626', help_text='Hex color code for accent color (e.g., #DC2626) - DEPRECATED: Use accent_material instead', max_length=7),
        ),
        migrations.AlterField(
            model_name='tracker',
            name='primary_color',
            field=models.CharField(default='#1E40AF', help_text='Hex color code for primary color (e.g., #1E40AF) - DEPRECATED: Use primary_material instead', max_length=7),
        ),
    ]
