# Generated by Django 5.2.4 on 2025-12-19 03:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inventory', '0036_tracker_accent_material_tracker_primary_material_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='tracker',
            name='accent_color',
            field=models.CharField(blank=True, default='', help_text='Hex color code for accent color (e.g., #DC2626) - DEPRECATED: Use accent_material instead', max_length=7),
        ),
        migrations.AlterField(
            model_name='tracker',
            name='primary_color',
            field=models.CharField(blank=True, default='#1E40AF', help_text='Hex color code for primary color (e.g., #1E40AF) - DEPRECATED: Use primary_material instead', max_length=7),
        ),
    ]
