# Generated by Django 5.2.4 on 2026-02-23 17:35

import django.core.validators
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inventory', '0037_alter_tracker_accent_color_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='ProjectBOMItem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('description', models.CharField(help_text="Part description as written in the creator's BOM (e.g., 'M3x8 SHCS')", max_length=255)),
                ('quantity_needed', models.PositiveIntegerField(default=1, help_text='Quantity required for this build', validators=[django.core.validators.MinValueValidator(1)])),
                ('status', models.CharField(choices=[('linked', 'Linked'), ('unlinked', 'Unlinked'), ('needs_purchase', 'Needs Purchase')], default='unlinked', help_text='linked=associated to inventory / unlinked=not yet matched / needs_purchase=flag to buy', max_length=20)),
                ('notes', models.TextField(blank=True, default='', help_text='Optional notes for this BOM item (e.g., variant notes from creator)')),
                ('sort_order', models.PositiveIntegerField(default=0, help_text='Display order within the project BOM')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('inventory_item', models.ForeignKey(blank=True, help_text='Optional link to an existing inventory item', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='bom_items', to='inventory.inventoryitem')),
                ('project', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='bom_items', to='inventory.project')),
            ],
            options={
                'verbose_name': 'Project BOM Item',
                'verbose_name_plural': 'Project BOM Items',
                'ordering': ['sort_order', 'id'],
            },
        ),
    ]
