# Generated by Django 5.2.4 on 2026-02-25 17:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inventory', '0038_add_project_bom_item'),
    ]

    operations = [
        migrations.AddField(
            model_name='projectbomitem',
            name='is_ordered',
            field=models.BooleanField(default=False, help_text='True when the item has been ordered but not yet received/linked to inventory'),
        ),
    ]
