# Generated by Django 5.2.4 on 2026-02-25 19:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inventory', '0039_projectbomitem_is_ordered'),
    ]

    operations = [
        migrations.AddField(
            model_name='inventoryitem',
            name='is_ordered',
            field=models.BooleanField(default=False, help_text='True when a replacement/restock order has been placed but not yet received'),
        ),
    ]
