# Generated by Django 5.2.4 on 2026-03-29 22:03

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inventory', '0041_remove_inventoryitem_quantity_min_validator'),
    ]

    operations = [
        migrations.CreateModel(
            name='TrackerFileImage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(help_text='Image file', upload_to='tracker_file_images/')),
                ('caption', models.CharField(blank=True, help_text='Optional caption for this image', max_length=255, null=True)),
                ('order', models.PositiveIntegerField(default=0, help_text='Display order (lower numbers shown first)')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('tracker_file', models.ForeignKey(help_text='The tracker file this image belongs to', on_delete=django.db.models.deletion.CASCADE, related_name='images', to='inventory.trackerfile')),
            ],
            options={
                'verbose_name': 'Tracker File Image',
                'verbose_name_plural': 'Tracker File Images',
                'ordering': ['order', 'created_at'],
            },
        ),
    ]
