# Generated by Django 5.2.4 on 2026-07-06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inventory', '0042_trackerfileimage'),
    ]

    operations = [
        migrations.AddField(
            model_name='tracker',
            name='generate_thumbnails_for_linked_files',
            field=models.BooleanField(default=False, help_text='Auto-generate thumbnails for GitHub-linked files by temporarily downloading each one (no local copy is kept). Off by default since it can be slow for large trackers.'),
        ),
        migrations.AddField(
            model_name='tracker',
            name='viewer_background',
            field=models.CharField(choices=[('dark', 'Dark'), ('light', 'Light')], default='dark', help_text='Background color for the 3D model viewer for files in this tracker', max_length=5),
        ),
        migrations.AddField(
            model_name='trackerfileimage',
            name='is_auto_generated',
            field=models.BooleanField(default=False, help_text='True if this image was auto-generated from the STL/3MF geometry, rather than manually uploaded. Auto-generated images are safe to replace/regenerate; manually uploaded ones are never touched by regeneration actions.'),
        ),
    ]
